### ISSUE TITLE
no DLL in the folder

### ISSUE THREAD

**Issue by zzhmx** [sair-lab/AirLine#3]
ImportError: DLL load failed while importing CRG: 找不到指定的模块。

**Comment by Lx017** [comment]
you should be able to load CRG/extractC/CRG.pyd (if it is some path issue it should be easy to fix), can I know your python version so I can test it? similar issues might occur if python version does not match the compiled pyd/dll configuration, I remember I used python 3.8. I am sorry about the confusion if you still get this please tell me. In the worst case you can try to build it yourself in VS, but it requires some configuration for pybind

**Comment by zzhmx** [comment]
Python 3.8 is indeed usable. But when I run the program now, it will display RuntimeError: CUDA out of memory. May I know how to change the parameters

**Comment by Lx017** [comment]
maybe you can try low-resolution images, as you cannot really change the size of model? Also please note when does the memory run out so that you can know if it occurs while loading the model or running on your images.

**Comment by zzhmx** [comment]
After recognizing an image for the first time, the results can be saved, but after entering the next cycle, there will be insufficient graphics memory

**Comment by zzhmx** [comment]
And I would like to know where the parameters corresponding to the threshold are. Thank you very much

**Comment by Lx017** [comment]
It seems that your GPU memory is quite limited. I am not sure if it can be resolved with lower precision model or manually delete cuda tensors after used. As for the parameters, THETARESOLUTION change numbers of channels of the orientation detector;
I assume that you are using airline_demo.py:
in lines like "edgeNp=(edgeNp>-2.5).astype(np.uint8)*255", -2.5 is the threshold for converting edge detection result to black and white;
in "linenum=crg.desGrow(outMap,edgeNp,THETADes[0].detach().cpu().numpy(),out,0.94,40,tempMem,tempMem2,tempMem3,THETARESOLUTION)#lineDetection1.detach().cpu().numpy()[0,0]", 0.94 is the orientation similarity threashold, the higher the more sensitive to orientation change, max is 1.0. 40 is the minimum number of pixels in a grown region to be recognized as valid so small regions will be ignored.
Sorry that I should have write them as separate variables, if you need more info i can update to you.
